title: Aaron's Resume
author: Aaron Sotzen
email: asotzen@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
Retired Army Combat Veteran with 10+ years of specialized project and manaement experience.
Proven leadership skills combined with an exceptional ability to manage multiple large-scale
projects, tasks, people, and priorities effectively. Trained in numerous leadership and techincal
skills to increase quality and improve processes.

# social links
github_username:  asotzen

show_excerpts: true # set to false to remove excerpts on the homepage
