title: Resume
author: Aaron Jeffrey Sotzen
email: asotzen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Seeking a goal-driven career within the programing field.

# social links
github_username:  asotzen

show_excerpts: true # set to false to remove excerpts on the homepage
